### ISSUE TITLE
Nullpointer exception

### ISSUE THREAD

**Issue by Freezzz** [applidium/Shutterbug#1]
Hi there, first thanks for grate lib! I've tryed your lib in production got few of those:
Reports this week: 559

```
java.lang.RuntimeException: An error occured while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:200)
at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:274)
at java.util.concurrent.FutureTask.setException(FutureTask.java:125)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:308)
at java.util.concurrent.FutureTask.run(FutureTask.java:138)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1088)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:581)
at java.lang.Thread.run(Thread.java:1019)
Caused by: java.lang.NullPointerException
at com.applidium.shutterbug.cache.ImageCache.storeToDisk(ImageCache.java:89)
at com.applidium.shutterbug.utils.ShutterbugManager$InputStreamHandlingTask.doInBackground(ShutterbugManager.java:159)
at com.applidium.shutterbug.utils.ShutterbugManager$InputStreamHandlingTask.doInBackground(ShutterbugManager.java:1)
at android.os.AsyncTask$2.call(AsyncTask.java:185)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:306)
... 4 more
```

**Comment by Ecco** [comment]
You're welcome. We never ran into this issue ourselves. Would you mind attaching a small sample code that reproduces this issue?

**Comment by danielsunyu** [comment]
Dear authors of Shutterbug,

```
I ran into exactly the same issue posted by Freezzz. I can't attach a sample code because it's hard to extract them from my production code. But I will describe the cause leading to it as best as I could. (though my English is not very fluent)

My app has a settings page and I put a image cache-clearing button there for users to clear cache at his will.
After I tap the button and navigate to my ListView-integrated page which is a different page with Shutterbug-powered, my app crashes immediately with the exactly same exception log as Freezzz. I guess that frequent clearing cache and downloading images will cause the crash.
I find out  that the "editor" object in the statement: (ImageCache.java line 95)
final OutputStream outputStream = editor.newOutputStream(0);
is null at runtime and thus crashes the app.

Hope it will provide a clue for you to fix them. Right now I just add additional general Exception catching block after yours chain.
```

**Comment by devrimtuncer** [comment]
Hi,
Same crash for me as @sunnyhust2005 detailed above at com.applidium.shutterbug.cache.ImageCache.storeToDisk();
final OutputStream outputStream = editor.newOutputStream(0); throws java.lang.NullPointerException, because;
mDiskCache.edit(cacheKey); returns null.

**Comment by acq** [comment]
Hi,
Thanks for bringing the problem to our attention.
I modified the error handling to prevent the NPE if mDiskCache.edit returns null (via commit 9766d3b) and it should no longer crash.
