### ISSUE TITLE
Issues with Amazon S3

### ISSUE THREAD

**Issue by kalvish21** [applidium/Shutterbug#10]
When I download an image from s3 in the below URL format:

https://s3.amazonaws.com/{{bucket name}}/image.png

Everything works perfectly. But I get errors with this format:

https://{{bucket name}}.s3.amazonaws.com/image.png

I get this error with teh second URL format:

java.net.UnknownHostException: https://{{bucket name}}.s3.amazonaws.com/image.png
at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:279)
at com.android.okhttp.internal.http.HttpEngine.sendSocketRequest(HttpEngine.java:255)
at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:206)
at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:345)
at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:296)
at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:179)
at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:246)
at com.applidium.shutterbug.downloader.ShutterbugDownloader$1.doInBackground(ShutterbugDownloader.java:65)
at com.applidium.shutterbug.downloader.ShutterbugDownloader$1.doInBackground(ShutterbugDownloader.java:52)
at android.os.AsyncTask$2.call(AsyncTask.java:288)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:841)

It works with the first URL but should work with both, they are both valid URL's.

**Comment by acq** [comment]
Hum, from what I can see, this problem is not originating inside Shutterbug, but inside Android's internal HTTP framework.

Can you test the following code with your bucket name : 

```
                URL imageUrl = new URL("https://{{bucket name}}.s3.amazonaws.com/image.png");
                URLConnection connection = imageUrl.openConnection();
                InputStream inputStream = connection.getInputStream();
```

If I'm right, this should yield you the same exception.

Also, does your bucket name contains "unusual" characters or is lengthy ? You can look here for restrictions on host names, which would explain why the second url is not working when the first is : http://en.wikipedia.org/wiki/Hostname#Restrictions_on_valid_host_names

**Comment by kalvish21** [comment]
I get the same error with the above as well.

The only characters that might seem different is that I have an _ in my bucket name. Perhaps that's it?

Interesting issue however. I use SDWebImage on the iOS side and I never saw this issue there...only with Android i'm seeing it now.

**Comment by acq** [comment]
Yes, I think this is your problem. You can put a hyphen (char: - ) in a domain name, but not an underscore (char: _ ). Different systems will handle non-standard names differently : from your experience, it seems iOS will accept them, while Android will reject them.
This was indeed interesting. Thanks for reporting this.

Luckily, you can still use the first format (https://s3.amazonaws.com/{{bucket name}}/image.png)
