### ISSUE TITLE
SDK10: java.lang.IllegalStateException: cache is closed 

### ISSUE THREAD

**Issue by djdance** [applidium/Shutterbug#13]
user on Android 2.3 (SDK10) periodically crashs with the follows
unfortunately, i do not know what to do.
can you help?

```
 java.lang.RuntimeException: An error occured while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:200)
at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:274)
at java.util.concurrent.FutureTask.setException(FutureTask.java:125)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:308)
at java.util.concurrent.FutureTask.run(FutureTask.java:138)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1088)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:581)
at java.lang.Thread.run(Thread.java:1019)
Caused by: java.lang.IllegalStateException: cache is closed
at com.applidium.shutterbug.cache.DiskLruCache.checkNotClosed(DiskLruCache.java:646)
at com.applidium.shutterbug.cache.DiskLruCache.get(DiskLruCache.java:452)
at com.applidium.shutterbug.cache.ImageCache$BitmapDecoderTask.doInBackground(ImageCache.java:145)
at com.applidium.shutterbug.cache.ImageCache$BitmapDecoderTask.doInBackground(ImageCache.java:1)
at android.os.AsyncTask$2.call(AsyncTask.java:185)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:306)
... 4 more
```

**Comment by djdance** [comment]
on SDK17 too

**Comment by djdance** [comment]
i tried, but not helps, try..catch not catched, whole app crashed.

```
            try {
                ImageCache.getSharedImageCache(getApplicationContext()).clear();
            } catch (Exception e) {
                Log.e(TAG,"incidents: err: "+e.toString());
            }
```
